sudo: required
services:
  - docker

before install:
  - docker build -t pradeep3015/docker-react-test -f Dockerfile.dev .

script:
  - docker run pradeep3015/docker-react-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-972744479426"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY